# This is a basic workflow to help you get started with Actions

name: Version Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '21'
          distribution: 'adopt'

      # Runs a single command using the runners shell
      - name: Grant execution permission for gradle
        run: chmod +x gradlew

      # Runs a set of commands using the runners shell
      - name: Building tomtom compose library in to .aar file
        run: |
          ./gradlew :tomtom-compose:assembleRelease

      - name: Publish release on github releases
        uses: softprops/action-gh-release@v2
        with:
          tag: ${{ github.ref_name }}
          files: tomtom-compose/build/outputs/aar/tomtom-compose-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
